/** Declaration file generated by dts-gen */
declare module 'mongoose-findorcreate' {
    import mongoose_findorcreate = require('mongoose-findorcreate');
}
declare function mongoose_findorcreate(schema: any, options: any, ...args: any[]): void;
